In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
DATA_PATH = "data/ml-100k"

In [3]:
ratings_df = pd.read_csv(
    os.path.join(DATA_PATH, "u.data"),
    "\t",
    names=["user_id", "movie_id", "rating", "timestamp"],
    engine="python",
    dtype=np.uint32,
)
users_df = pd.read_csv(
    os.path.join(DATA_PATH, "u.user"),
    "|",
    names=["user_id", "age", "gender", "occupation", "zip_code"],
    engine="python",
)
movies_list = [
    i.strip().split("|")
    for i in open(
        os.path.join(DATA_PATH, "u.item"), encoding="latin-1"
    ).readlines()
]
movies_df = pd.DataFrame(
    movies_list,
    columns=[
        "movie_id",
        "title",
        "release_date",
        "video_release_date",
        "imdb_url",
        "unknown",
        "Action",
        "Adventure",
        "Animation",
        "Childrens",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Fantasy",
        "Film_Noir",
        "Horror",
        "Musical",
        "Mystery",
        "Romance",
        "Sci-Fi",
        "Thriller",
        "War",
        "Western",
    ],
)
movies_df["movie_id"] = movies_df["movie_id"].apply(pd.to_numeric)

movies_encoder = preprocessing.LabelEncoder()
movies_encoder.fit(movies_df["movie_id"].values)

movies_df["movie_id"] = movies_encoder.transform(movies_df["movie_id"].values)
ratings_df["movie_id"] = movies_encoder.transform(ratings_df["movie_id"].values)

users_encoder = preprocessing.LabelEncoder()
users_encoder.fit(users_df["user_id"].values)

users_df["user_id"] = users_encoder.transform(users_df["user_id"].values)
ratings_df["user_id"] = users_encoder.transform(ratings_df["user_id"].values)

ratings_df = ratings_df.applymap(int)
#ratings_df = ratings_df.sort_values("timestamp")

movies_df = movies_df.drop(columns=["release_date", "video_release_date", "imdb_url"])

/data/miniconda3/envs/recsysrl/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
from matplotlib import pyplot
from numpy.random import normal
from numpy import mean
from numpy import std
from scipy.stats import norm
# generate a sample
# calculate parameters
sample_mean = mean(sample)
sample_std = std(sample)
print('Mean=%.3f, Standard Deviation=%.3f' % (sample_mean, sample_std))
# define the distribution
dist = norm(sample_mean, sample_std)
# sample probabilities for a range of outcomes
values = [value for value in range(30, 70)]
probabilities = [dist.pdf(value) for value in values]
# plot the histogram and pdf
pyplot.hist(sample, bins=10, density=True)
pyplot.plot(values, probabilities)
pyplot.show()

In [145]:
import plotly.express as px
r = geom.rvs(0.35, size=movies_df.shape[0])
px.histogram(r%10)

In [152]:
r = r%10
r = np.where(r==0,10,r)

In [153]:
px.histogram(r)

In [154]:
movies_df["group"] = r

In [160]:
movies_groups = {
    row[0]: row[-1]
    for index, row in movies_df.iterrows()
}
movies_groups

{0: 3,
 1: 2,
 2: 1,
 3: 7,
 4: 2,
 5: 8,
 6: 5,
 7: 10,
 8: 2,
 9: 2,
 10: 1,
 11: 1,
 12: 2,
 13: 7,
 14: 2,
 15: 3,
 16: 4,
 17: 1,
 18: 2,
 19: 5,
 20: 9,
 21: 3,
 22: 1,
 23: 4,
 24: 3,
 25: 6,
 26: 4,
 27: 2,
 28: 3,
 29: 6,
 30: 2,
 31: 3,
 32: 2,
 33: 3,
 34: 1,
 35: 1,
 36: 3,
 37: 5,
 38: 5,
 39: 2,
 40: 2,
 41: 1,
 42: 1,
 43: 6,
 44: 4,
 45: 3,
 46: 1,
 47: 5,
 48: 1,
 49: 1,
 50: 5,
 51: 3,
 52: 1,
 53: 2,
 54: 4,
 55: 1,
 56: 3,
 57: 2,
 58: 3,
 59: 1,
 60: 3,
 61: 2,
 62: 3,
 63: 1,
 64: 1,
 65: 9,
 66: 7,
 67: 1,
 68: 3,
 69: 4,
 70: 4,
 71: 1,
 72: 1,
 73: 4,
 74: 1,
 75: 2,
 76: 1,
 77: 2,
 78: 1,
 79: 2,
 80: 1,
 81: 4,
 82: 1,
 83: 1,
 84: 1,
 85: 10,
 86: 1,
 87: 1,
 88: 2,
 89: 1,
 90: 2,
 91: 4,
 92: 3,
 93: 1,
 94: 7,
 95: 2,
 96: 1,
 97: 4,
 98: 3,
 99: 2,
 100: 1,
 101: 1,
 102: 4,
 103: 1,
 104: 1,
 105: 2,
 106: 1,
 107: 3,
 108: 4,
 109: 1,
 110: 1,
 111: 3,
 112: 2,
 113: 1,
 114: 3,
 115: 1,
 116: 2,
 117: 2,
 118: 2,
 119: 3,
 120: 1,
 121: 2,
 122: 1,
 

In [162]:
import pickle
with open("data/ml-100k/movies_groups.pkl", "wb") as file:
    pickle.dump(movies_groups, file)

In [213]:
fc = {k: 0.1 for k in range(1, 10 + 1)}
gc = {k: 1 for k in range(1, 10 + 1)}

In [219]:
gc[1] = 1

In [220]:
fair = np.array(list(fc.values())) * (
    np.sum(np.array(list(gc.values()))) - 1
) - np.array(list(gc.values()))

fair

array([-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1])

In [221]:
np.argmax(fair[~ (fair < 0)])

ValueError: attempt to get argmax of an empty sequence

In [172]:
np.array(list(fc.values()))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [198]:
(np.array(list(fc.values())) / np.sum(np.array(list(fc.values())))) - (np.array(list(gc.values())) / np.sum(list(gc.values())))

array([ 0.1       , -0.01111111, -0.01111111, -0.01111111, -0.01111111,
       -0.01111111, -0.01111111, -0.01111111, -0.01111111, -0.01111111])

In [177]:
total_exp = np.sum(list(gc.values()))
np.sum(
    np.array(list(fc.values()))
    * np.log(1 + np.array(list(gc.values())) / total_exp)
)

0.9531017980432495

In [191]:
for group in range(1, 10):
    gc[group] = 0

In [46]:
ratings_df[ratings_df["user_id"] == 159].head(10)

user_id  movie_id  rating  timestamp
29        159       233       5  876861185
108       159       173       5  876860807
156       159       134       4  876860807
196       159       718       3  876857977
436       159       459       2  876861185
919       159       461       4  876858346
1349      159       159       5  876862078
1500      159       429       5  876861799
1917      159        55       5  876770222
1966      159       116       4  876767822

In [40]:
df = ratings_df.copy()
df = df[df["rating"] >= 4]
df_list = []
for g, df_g in df.groupby("user_id"):
    list_of_indexes = []
    df_g["movie_id"].rolling(5, min_periods=1).apply(
        (lambda x: list_of_indexes.append(x.astype(int).tolist()) or 0),
        raw=False,
    )
    df_g["item_id_history"] = list_of_indexes
    df_g["item_id_history"] = df_g["item_id_history"].shift(1)

    Item_prev = (
        df_g["item_id_history"]
        .apply(lambda x: [] if x is np.nan else x)
        .apply(lambda x: ([""] * (5 - len(x)) + x)[:5])
    )
    df_list.append(Item_prev)

df["item_id_history"] = pd.concat(df_list)


In [41]:
ratings_df["item_id_history"] = df["item_id_history"]
ratings_df

user_id  movie_id  rating  timestamp            item_id_history
214        258       254       4  874724710                 [, , , , ]
83965      258       285       4  874724727              [, , , , 254]
43027      258       297       4  874724754           [, , , 254, 285]
21396      258       184       4  874724781        [, , 254, 285, 297]
82655      258       172       4  874724843     [, 254, 285, 297, 184]
...        ...       ...     ...        ...                        ...
46773      728       688       4  893286638  [353, 321, 361, 299, 332]
73008      728       312       3  893286638                        NaN
46574      728       327       3  893286638                        NaN
64312      728       747       4  893286638  [321, 361, 299, 332, 688]
79208      728       271       4  893286638  [361, 299, 332, 688, 747]

[100000 rows x 5 columns]

In [42]:
ratings_df = ratings_df.fillna(method="ffill")
ratings_df

user_id  movie_id  rating  timestamp            item_id_history
214        258       254       4  874724710                 [, , , , ]
83965      258       285       4  874724727              [, , , , 254]
43027      258       297       4  874724754           [, , , 254, 285]
21396      258       184       4  874724781        [, , 254, 285, 297]
82655      258       172       4  874724843     [, 254, 285, 297, 184]
...        ...       ...     ...        ...                        ...
46773      728       688       4  893286638  [353, 321, 361, 299, 332]
73008      728       312       3  893286638  [353, 321, 361, 299, 332]
46574      728       327       3  893286638  [353, 321, 361, 299, 332]
64312      728       747       4  893286638  [321, 361, 299, 332, 688]
79208      728       271       4  893286638  [361, 299, 332, 688, 747]

[100000 rows x 5 columns]